name: Firebase Preview Deploy
description: 'Build and deploy the Android app to Firebase App Distribution using Fastlane'

inputs:
  ANDROID_FIREBASE_PROJECT_NUMBER:
    description: 'Firebase project number'
    required: true
  ANDROID_FIREBASE_APP_ID:
    description: 'Firebase app ID'
    required: true
  ANDROID_FIREBASE_PROJECT_ID:
    description: 'Firebase project ID'
    required: true
  ANDROID_FIREBASE_APP_PACKAGE:
    description: 'Firebase app package name'
    required: true
  ANDROID_FIREBASE_API_KEY:
    description: 'Firebase API key'
    required: true
  OSTORLAB_API_KEY:
    description: 'API key for Ostorlab vulnerability scans'
    required: true
  ANDROID_GCP_JSON_BASE64:
    description: 'GCP JSON key (base64 encoded)'
    required: true
  PR_NUMBER:
    description: 'Pull request number'
    required: true
  PR_TITLE:
    description: 'Pull request title'
    required: true
  RELEASE_NOTES:
    description: 'Release notes for the build'
    required: true
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Set up Fastlane
      uses: ./.github/actions/setup-fastlane

    - name: Export Release Notes
      shell: bash
      run: |
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
        echo "${{ inputs.RELEASE_NOTES }}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Decode and save GCP service account key
      shell: bash
      run: |
        echo "${{ inputs.ANDROID_GCP_JSON_BASE64 }}" | base64 --decode > /tmp/gcp_key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_key.json" >> $GITHUB_ENV

    - name: Gradle cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build preview APK (no upload)
      id: build_apk
      working-directory: android
      env:
        FIREBASE_API_KEY: "${{ inputs.ANDROID_FIREBASE_API_KEY }}"
        ANDROID_FIREBASE_PROJECT_NUMBER: "${{ inputs.ANDROID_FIREBASE_PROJECT_NUMBER }}"
        ANDROID_FIREBASE_APP_ID: "${{ inputs.ANDROID_FIREBASE_APP_ID }}"
        ANDROID_JSON_KEY_FILE: "/tmp/gcp_key.json"
        FIREBASE_SKIP_UPLOAD: "1"
        APK_PATH_FILE: "/tmp/firebase_apk_path.txt"
      shell: bash
      run: |
        bundle exec fastlane android pr_deploy \
          pr_number:"${{ inputs.PR_NUMBER }}" \
          pr_title:"${{ inputs.PR_TITLE }}" \
          project_number:"${{ inputs.ANDROID_FIREBASE_PROJECT_NUMBER }}" \
          app_id:"${{ inputs.ANDROID_FIREBASE_APP_ID }}"
        echo "apk_path=$(cat /tmp/firebase_apk_path.txt)" >> "$GITHUB_OUTPUT"

    - name: Mobile security scan (Trivy + Ostorlab)
      uses: ./.github/actions/mobile-scan
      with:
        android-apk-path: ${{ steps.build_apk.outputs.apk_path }}
        ostorlab-api-key: ${{ inputs.OSTORLAB_API_KEY }}

    - name: Upload preview APK to Firebase App Distribution
      working-directory: android
      env:
        FIREBASE_API_KEY: "${{ inputs.ANDROID_FIREBASE_API_KEY }}"
        ANDROID_FIREBASE_PROJECT_NUMBER: "${{ inputs.ANDROID_FIREBASE_PROJECT_NUMBER }}"
        ANDROID_FIREBASE_APP_ID: "${{ inputs.ANDROID_FIREBASE_APP_ID }}"
        ANDROID_JSON_KEY_FILE: "/tmp/gcp_key.json"
        APK_PATH: "${{ steps.build_apk.outputs.apk_path }}"
      shell: bash
      run: |
        bundle exec fastlane android pr_deploy \
          pr_number:"${{ inputs.PR_NUMBER }}" \
          pr_title:"${{ inputs.PR_TITLE }}" \
          project_number:"${{ inputs.ANDROID_FIREBASE_PROJECT_NUMBER }}" \
          app_id:"${{ inputs.ANDROID_FIREBASE_APP_ID }}"

    - name: Cleanup sensitive files
      if: always()
      shell: bash
      run: rm -f /tmp/gcp_key.json
