name: "Deploy iOS App on App Store"
description: "Build and deploy the iOS app to Production using Fastlane"

inputs:
  IOS_APP_STORE_CONNECT_API_KEY_B64:
    required: true
    description: "API Key contents for App Store Connect"
  IOS_APP_STORE_CONNECT_API_KEY_ID:
    required: true
    description: "API Key ID for App Store Connect"
  IOS_APP_STORE_CONNECT_ISSUER_ID:
    required: true
    description: "Issuer ID for App Store Connect"
  IOS_MATCH_REPOSITORY_URL:
    required: true
    description: "Repository URL for Match"
  IOS_MATCH_KEYCHAIN_PASSWORD:
    required: true
    description: "Keychain password for Match"
  IOS_MATCH_PASSWORD:
    required: true
    description: "Password for Match"
  IOS_APPLE_ID_PRODUCTION:
    required: true
    description: "Apple ID for production deployment"
  IOS_APP_IDENTIFIER_PRODUCTION:
    required: true
    description: "App Identifier for production deployment"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: "22.13.1"
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-v2-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-v2-

    - name: Restore Pods cache
      uses: actions/cache@v4
      with:
        path: |
          ios/Pods
          ~/Library/Caches/CocoaPods
          ~/.cocoapods
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install node modules
      run: |
        yarn cache clean
        yarn install --force
        patch -p1 < patches/boost.podspec.patch
      shell: bash
      env:
        CI: true

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
        cd ios
        pod install
      shell: bash

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.4"
        bundler-cache: true

    - name: Install Fastlane
      run: |
        gem install bundler
        cd ios
        bundle install
      shell: bash
      env:
        CI: true

    - name: Build and deploy the iOS app to Production
      run: |
        cd ios
        bundle exec fastlane deploy_ios_production
      shell: bash
      env:
        CI: true
        IOS_APP_STORE_CONNECT_API_KEY_B64: ${{ inputs.IOS_APP_STORE_CONNECT_API_KEY_B64 }}
        IOS_APP_STORE_CONNECT_API_KEY_ID: ${{ inputs.IOS_APP_STORE_CONNECT_API_KEY_ID }}
        IOS_APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ inputs.IOS_APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        IOS_MATCH_REPOSITORY_URL: ${{ inputs.IOS_MATCH_REPOSITORY_URL }}
        IOS_KEYCHAIN_PASSWORD: ${{ inputs.IOS_KEYCHAIN_PASSWORD }}
        IOS_MATCH_PASSWORD: ${{ inputs.IOS_MATCH_PASSWORD }}
        IOS_APPLE_ID_PRODUCTION: ${{ secrets.IOS_APPLE_ID_PRODUCTION }}
        IOS_APP_IDENTIFIER_PRODUCTION: ${{ secrets.IOS_APP_IDENTIFIER_PRODUCTION }}