name: Release Notes Check
description: Checks if release notes file exists for the current version and outputs the content.

inputs:
  version_file:
    description: 'Path to the version file (default: package.json)'
    required: false
    default: 'package.json'
  notes_dir:
    description: 'Directory containing release notes (default: docs/release_notes)'
    required: false
    default: 'docs/release_notes'
  notes_ext:
    description: 'Release notes file extension (default: .md)'
    required: false
    default: '.md'

outputs:
  release_notes:
    description: 'Content of the release notes file'
    value: ${{ steps.check_notes.outputs.release_notes }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from JSON
      id: get_version
      shell: bash
      run: |
        VERSION=$(jq -r .version < "${{ inputs.version_file }}")
        echo "Extracted version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Check for release notes file
      id: check_notes
      shell: bash
      run: |
        NOTES_FILE="${{ inputs.notes_dir }}/${{ steps.get_version.outputs.version }}${{ inputs.notes_ext }}"
        echo "Checking release notes file: $NOTES_FILE"

        if [ ! -f "$NOTES_FILE" ]; then
          echo "::error::❌ Release notes file not found: $NOTES_FILE"
          exit 1
        fi

        if [ ! -s "$NOTES_FILE" ]; then
          echo "::error::❌ Release notes file is empty: $NOTES_FILE"
          exit 1
        fi

        echo "✅ Release notes file found: $NOTES_FILE"

        CONTENT=$(cat "$NOTES_FILE")
        {
          echo 'release_notes<<EOF'
          echo "$CONTENT"
          echo 'EOF'
        } >> $GITHUB_OUTPUT
