default_platform(:ios)

platform :ios do
  desc "Fetch certificates for CI"
  lane :ci_signing_setup do
    match(type: "appstore", readonly: true)
    match(type: "development", readonly: true)
  end

  desc "Build and upload to TestFlight"
  lane :pr_deploy do
    match(type: "appstore", readonly: true)
    update_project_provisioning(
        xcodeproj: "Boilerplate.xcodeproj",
        target_filter: "Boilerplate", # your target name
        build_configuration: "Release",
        signing_style: "manual",
        code_sign_identity: "Apple Distribution",     # or Apple Development
        build_settings: {
            "CODE_SIGN_STYLE" => "Manual"
        },
        profile_mapping: {
            "Boilerplate" => "match AppStore com.bettrsw.boilerplate"
        }  
    )
    build_app(
      scheme: "Boilerplate", 
      export_method: "app-store"
    )
    upload_to_testflight(
      changelog: "PR Build",
      distribute_external: true,
    )

  end
end
