default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply(track: 'production', aab: "./app/build/outputs/bundle/release/app-release.aab")
  end
end
