name: "Inject Doppler Secrets"
description: "Fetch and inject Doppler secrets into the environment for a specified directory."
inputs:
  doppler_token:
    description: "Doppler service token for fetching secrets"
    required: true
  working_directory:
    description: "Directory where the .env file should be created"
    default: "."
    required: false
  doppler_project:
    description: "Doppler project name (e.g., backend, frontend)"
    required: true
  doppler_environment:
    description: "Doppler environment (e.g., production, staging)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v3
    
    - name: Inject Doppler secrets into environment
      shell: bash
      run: |
        set -euo pipefail

        WORKDIR="${{ inputs.working_directory }}"
        ENV_FILE="${WORKDIR}/.env"

        echo "Fetching Doppler secrets for project: ${{ inputs.doppler_project }}, environment: ${{ inputs.doppler_environment }}"
        
        # Download secrets for the specified environment and project
        doppler secrets download --format=env --no-file \
          --project=${{ inputs.doppler_project }} \
          --config=${{ inputs.doppler_environment }} > .doppler_env
        
        # Update the existing .env file with values from Doppler secrets
        if [ -f "$ENV_FILE" ]; then
          while IFS='=' read -r key value; do
            # Skip empty lines and comments
            [[ -z "$key" || "$key" =~ ^# ]] && continue

            SAFE_KEY=$(printf '%s' "$key" | sed 's/[.[\*^$(){}+?|/]/\\&/g')
            
            if grep -Eq "^${SAFE_KEY}=" "$ENV_FILE"; then
              # Escape dynamic values for safe sed replacement.
              SAFE_VALUE=$(printf '%s' "$value" | sed 's/[&|\\]/\\&/g')

              # macOS (BSD) sed requires '' after -i, Linux (GNU) sed doesn't
              if [[ "$OSTYPE" == "darwin"* ]]; then
                sed -i '' "s|^${SAFE_KEY}=.*|${key}=${SAFE_VALUE}|" "$ENV_FILE"
              else
                sed -i "s|^${SAFE_KEY}=.*|${key}=${SAFE_VALUE}|" "$ENV_FILE"
              fi
            else
              echo "$key=$value" >> "$ENV_FILE"
            fi
          done < .doppler_env
        else
          mv .doppler_env "$ENV_FILE"
        fi
        
        # Clean up the temporary file
        rm -f .doppler_env
      env:
        DOPPLER_TOKEN: ${{ inputs.doppler_token }}
    
    - name: Verify .env file (Safe Verification)
      shell: bash
      run: |
        set -euo pipefail
        echo "Keys in .env:"
        grep -o '^[^=]*' "${{ inputs.working_directory }}/.env"
