name: Cleanup Firebase Release on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    env:
      ANDROID_APP_PACKAGE: ${{ secrets.ANDROID_APP_PACKAGE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - uses: ./.github/actions/setup-fastlane
      
      - name: Set Gradle signing environment variables
        run:  echo "ANDROID_JSON_KEY_FILE=$(pwd)/play_store.json" >> $GITHUB_ENV

      - name: Decode Google Play JSON Key
        run: echo "${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}" | base64 --decode > play_store.json

      - name: Cleanup Firebase App Distribution for PR
        working-directory: android
        run: bundle exec fastlane android pr_cleanup pr_number:"${{ github.event.pull_request.number }}" json_key_file:"${{ env.ANDROID_JSON_KEY_FILE }}" package_name:"${{ env.ANDROID_APP_PACKAGE }}"

